export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const ROBOT_STATE_PENDING = 'ROBOT_STATE_PENDING';
export const ROBOT_STATE_FAILED = 'ROBOT_STATE_FAILED';
export const ROBOT_STATE_SUCCESS = 'ROBOT_STATE_SUCCESS'